language: haxe

os:
  - linux

dist: trusty

haxe:
  - "4.1.2"
  - development # the latest build of the development branch in http://build.haxe.org/

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib git sage-agi https://github.com/sgalland/sage-agi.git
  - haxelib install openfl
  - haxelib install hxcpp
  - echo "y" | haxelib run openfl setup &> log.txt || cat log.txt

script:
  - haxelib run openfl build linux -release